### ISSUE TITLE
How can I only download the videos/images and their action annotation in your dataset?

### ISSUE THREAD

**Issue by monacv** [jpnm561/HAR-UP#2]

**Comment by jpnm561** [comment]
Hi! You can use the **dataBaseDownload()** function in the **Downloader_pydrive.py** script to get all the images: 

`local_path = "your_local_path"`
`dataBaseDownload(local_path, csv_files=False, cameras=True)`

You can find a zip file with all the annotated time stamps (subject, activity, trial, tag) with this link: https://drive.google.com/file/d/10LeSHGXcq6_euRxCa3xqKG6HtRgB5ke1/view?usp=sharing
