### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by saniazahan** [jpnm561/HAR-UP#3]
Hi 
I followed all the instructions to download. 
Set up pydrive and have put all the files in the same directory.
But when I ran Downloader_pydrive.py file I get the following error.
```
An error ocurred: Please specify credentials file to read
An error ocurred while connecting to Google Drive
```
This line https://github.com/jpnm561/HAR-UP/blob/4a8d706051cc202c34b6cadec24e4d6040e78fa0/DataBaseDownload/Downloader_pydrive.py#L29
I don't have a 'credentials.json' file. What is it and how should I set it up.
Could you please suggest what is the problem. Thanks.

**Comment by saniazahan** [comment]
settings.yaml has these lines 
```
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
```
but no credentials.json is saved when I am running Downloader_pydrive.py file

**Comment by saniazahan** [comment]
I tested with a sample code to see if everything is okay at my end and it works and a file is uploaded

```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
drive = GoogleDrive(gauth)

folder = 'used a id of a folder in my drive'

file1 = drive.CreateFile({'parents' : [{'id' : folder}], 'title' : 'hello2.txt'})
file1.SetContentString('Hello world!, this is my second file')
file1.Upload()
```

**Comment by saniazahan** [comment]
This line 
https://github.com/jpnm561/HAR-UP/blob/4a8d706051cc202c34b6cadec24e4d6040e78fa0/DataBaseDownload/Downloader_pydrive.py#L43

needs to be modified as 

gauth.SaveCredentialsFile('credentials.json')

**Comment by josepablonm** [comment]
Hello!

Sorry for not responding earlier, I hadn't seen your thread. However I'm glad that you found a solution! I'll be adding your correction to the code.
